autoload colors; colors

for COLOR in RED GREEN BLUE YELLOW MAGENTA CYAN BLACK WHITE; do
	eval PR_$COLOR='%{$fg_no_bold[${(L)COLOR}]%}'
	eval PR_BOLD_$COLOR='%{$fg_bold[${(L)COLOR}]%}'
done

eval RESET='$reset_color'
export PR_RED PR_GREEN PR_BLUE PR_YELLOW PR_WHITE PR_BLACK
export PR_BOLD_RED PR_BOLD_GREEN PR_BOLD_BLUE PR_BOLD_YELLOW PR_BOLD_WHITE PR_BOLD_BLACK

#Clear LSCOLORS
unset LSCOLORS

export CLICOLOR=1
export LS_COLORS=exfxcxdxbxegedabagacad

autoload -U compinit && compinit

function prompt_char {
    git branch >/dev/null 2>/dev/null && echo '±' && return
    hg root >/dev/null 2>/dev/null && echo '☿' && return
    echo '🍺 '
}

PROMPT="%{$fg[magenta]%}%n%{$reset_color%} at %{$fg[yellow]%}%m%{$reset_color%} in %{$fg[green]%}%~ %{$reset_color%}$(prompt_char) "

export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_77`
export JAVA_OPTS=" -Xms512M -Xmx2048M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=$HOME/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
export PATH=$HOME/Library/Haskell/bin:$JAVA_HOME/bin:$HOME/dev/scala/scala-2.11.8/bin:$HOME/bin:/usr/local/bin:$PATH

alias ls='ls -alCF'
alias act=activator
alias dot='cd ~/dotfiles/zsh'
alias scala='scala -Dscala.color=true'
